#!/bin/sh

export PGPASSWORD=@nnihilation2013

/opt/PostgresPlus/9.2AS/bin/psql -h 10.254.0.225 -U kudos_adm -p 5432 kudos  <<EDD
INSERT INTO cube_hours2
select school_type,null,null,null,null,level,year,period,null,null,count(*) total,count(CASE WHEN lesson_begin is not null THEN 1 ELSE null END) hasdate,count(CASE WHEN lesson_status = 'RUNNING' THEN 1 ELSE null END) as running from pre_cube_hours group by school_type,level,year,period;;
EDD
