#!/bin/sh

export PGPASSWORD=@nnihilation2013

/opt/PostgresPlus/9.2AS/bin/psql -h 10.254.0.225 -U kudos_adm -p 5432 kudos  <<EDD
INSERT INTO cube_mark2
select school_type,district,region,null,null,null,year,period,null,null,	count(*) total,sum(mark),count(CASE WHEN mark = 5 THEN 1 ELSE null END) five,count(CASE WHEN mark = 4 THEN 1 ELSE null END) four,count(CASE WHEN mark = 3 THEN 1 ELSE null END) three,count(CASE WHEN mark = 2 THEN 1 ELSE null END) two from pre_cube_mark group by school_type,district,region,year,period;
EDD
